### Site info:
title: 装修好手册
tagline: 装修好手册是你房屋装修的好帮手。
author: 装修好手册
description: "装修好手册，是您装修房屋的好帮手。" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "装修 好手册 装修助手"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zhuangxiu.haoshouce.com" # the base hostname & protocol for your site
locale: zh_CN # en_US

### Personal info and site tools info:
favicon: "/images/favicon.ico"
aboutme_photo: /images/me.png # your photo.
aboutme: 装修好手册，整理收集了房屋装修方面的一些知识，供大家参考！ # these are shown on aboutme-sidebar.

### Site setting:
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "cn" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    cn:
      Aboutme: "关于本站"
      Archives: "存档"
      Blogroll: "友情链接"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "更早的"
      Next: "更新的"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "
      Baidu_search: "站内搜索"
### your Blogroll info, only name can shown on the page.

Blogroll:
      - name: 百度
        href: http://www.baidu.com
        title: baidu

### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
excerpt_separator: <!-- more -->
